apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-09-18T15:11:35Z"
  labels:
    app: nginx
  name: nginx
  namespace: learningkubernetes
  resourceVersion: "421344"
  selfLink: /api/v1/namespaces/learningkubernetes/services/nginx
  uid: c36bdc6f-abd2-4af6-bf10-5f4f46f77962
spec:
  clusterIP: 10.100.51.226
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32146
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer:
    ingress:
    - hostname: localhost
